FROM jenkins/jenkins:latest

USER root

RUN apt-get update && apt-get install -y \
    jq \
    curl \
    git \
    maven \
    docker.io \
    docker-compose \
    && rm -rf /var/lib/apt/lists/*

USER jenkins